#ifndef COLORES_H_INCLUDED
#define COLORES_H_INCLUDED

#define FG_ROJO FOREGROUND_RED
#define FG_CELESTE FOREGROUND_GREEN|FOREGROUND_BLUE
#define FG_VIOLETA FOREGROUND_RED|FOREGROUND_BLUE
#define FG_AMARILLO FOREGROUND_RED|FOREGROUND_GREEN
#define FG_VERDE FOREGROUND_GREEN
#define FG_AZUL FOREGROUND_BLUE
#define FG_BLANCO FOREGROUND_RED|FOREGROUND_GREEN|FOREGROUND_BLUE
#define FG_NEGRO 0

#endif // COLORES_H_INCLUDED
